galaxy_info:
  role_name: datadisk-n01610736
  author: Ruchika Soni
  description: A parameterized Ansible role to partition and mount data disks.
  min_ansible_version: 2.10
  platforms:
    - name: Linux
      versions:
        - all
  galaxy_tags:
    - disk
    - partition
    - mount
