---
- name: Create cloudadmins group
  group:
    name: "{{ item.group_name }}"
    state: present
  loop: "{{ users_info }}"
    
- name: Create user accounts
  user:
    name: "{{ item.username }}"
    groups: "{{ item.group_name }}"
    state: "{{ item.state }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: ~/.ssh/id_rsa
    ssh_key_comment: "{{ item.username }}"
    password: ""
    shell: /bin/bash
  loop: "{{ users_info }}"

- name: Add SSH keys for users
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
    state: present
  loop: "{{ users_info }}"

- name: Validate the sudoers file before saving, uncomment 
  lineinfile:
    path: "{{ item.path }}"
    line: ' %cloudadmins ALL=(ALL) NOPASSWD: ALL'
    create: yes
    validate: "{{ item.validate }}"
  loop: "{{ sudoers_update }}"
