---
- name: Install Apache web server
  dnf:
    name: httpd
    state: present

- name: Copy FQDN to Apache web server
  shell: | 
    echo $HOSTNAME > index.html 
    cp index.html /var/www/html/index.html
  notify: 
    - restart_apache

- name: Set permissions on index.html files
  file:
    path: "/var/www/html/index.html"
    mode: "0444"

- name: Start Apache web server
  service:
    name: httpd
    state: started
    enabled: yes
