---
- name: Create a partition
  parted:
    device: "{{ item.device }}"
    number: "{{ item.number }}"
    state: present
    part_start: "{{ item.part_start }}"
    part_end: "{{ item.part_end }}"
  loop: "{{ disks_info }}"

- name: Format the disk
  filesystem: 
    fstype: "{{ item.fstype }}"
    dev: "{{ item.partition }}"
  loop: "{{ disks_info }}"

- name: Create directory 
  file: 
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  loop: "{{ disks_info }}"

- name: Mount the partition
  mount: 
    path: "{{ item.path }}"
    src: "{{ item.partition }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  loop: "{{ disks_info }}"
